version: "3.3"
services:
  frontend:
    image: kjartaneinarsson/frontend
    deploy:
      replicas: 1
    ports:
      - "3000"
    environment:
      - REACT_APP_BACKEND_HOST=${BACKEND_HOST}
    networks:
      - loadbalancing
    volumes:
      - ./frontend/:/frontend/dev
      - /frontend/dev/node_modules/

  backend:
    image: kjartaneinarsson/backend
    deploy:
      replicas: 1
    ports:
      - "4000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ADMIN=${DB_ADMIN}
      - DB_ADMIN_PASS=${DB_ADMIN_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - loadbalancing
    volumes:
      - ./backend/:/backend/dev
      - /backend/dev/node_modules/
    depends_on: [rabbitmq]

  order_handler:
    image: kjartaneinarsson/order_handler
    ports:
      - "5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ADMIN=${DB_ADMIN}
      - DB_ADMIN_PASS=${DB_ADMIN_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - loadbalancing
    volumes:
      - ./order_handler/:/order_handler/dev
      - /order_handler/dev/node_modules/
    depends_on: [rabbitmq]

  database:
    image: kjartaneinarsson/database
    build: .
    ports:
      - "27017:27017"
    networks:
      - loadbalancing

  rabbitmq:
    image: kjartaneinarsson/rabbitmq
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - loadbalancing
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 25

  matching_engine:
    image: kjartaneinarsson/matching_engine
    ports:
      - "7000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    networks:
      - loadbalancing
    volumes:
      - ./matching_engine/:/matching_engine/dev
      - /matching_engine/dev/node_modules/
    depends_on: [rabbitmq]
    
  nginx:
    image: kjartaneinarsson/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
    depends_on:
      - frontend
      - backend
      - matching_engine
      - order_handler
    networks:
      - loadbalancing

networks:
  loadbalancing:
  

volumes:
  db_data:
