env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./backend/tsconfig.json"
  # tsconfigRootDir: __dirname
  # tried to solve the tsconfig not found in app.ts
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: "detect"
rules: {}
